server.port: 7001
spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

logging:
  level:
    root: INFO
    com.sandcastle: DEBUG

---
spring.config.activate.on-profile: docker
server.port: 8080
spring.data.mongodb.host: mongodb
