server.port: 7000
server.error.include-message: always

app:
  product:
    host: localhost
    port: 7001
  recommendation:
    host: localhost
    port: 7002
  review:
    host: localhost
    port: 7003

logging:
  level:
    root: INFO
    com.sandcastle: DEBUG

---
spring.config.activate.on-profile: docker
server.port: 8080
app:
  product:
    host: product
    port: 8080
  recommendation:
    host: recommendation
    port: 8080
  review:
    host: review
    port: 8080