server.port: 7002
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db
  auto-index-creation: true

logging:
  level:
    root: INFO
    com.sandcastle: DEBUG
---
spring.config.activate.on-profile: docker
server.port: 8080
spring.data.mongodb.host: mongodb