server.port: 7003
server.error.include-message: always

# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

logging:
  level:
    root: INFO
    com.sandcastle: DEBUG
---
spring.config.activate.on-profile: docker
server.port: 8080
spring.datasource:
  url: jdbc:mysql://mysql/review-db